### ISSUE TITLE
Can UpdateAndGet return an array of entity

### ISSUE THREAD

**Issue by ssraj326** [dj-nitehawk/MongoDB.Entities#110]
Hi,
Is there a way UpdateAndGet call can return multiple items. If you try to update multiple items, it doesnt get you all the updated ones. Would be nice if it can return all the updated /matching items.

**Comment by dj-nitehawk** [comment]
unfortunately the official driver doesn't offer that functionality as a single method. so it's not possible for this library to do it in a single db call either. 

you will have to do it yourself as two separate operations in your own code.

I'm not sure why the official driver doesn't offer it. my assumption is probably due to possible concucency issues.

**Comment by ssraj326** [comment]
thanks for the update.
