### ISSUE TITLE
Feature request: Transaction emulate flag.

### ISSUE THREAD

**Issue by rzer** [dj-nitehawk/MongoDB.Entities#113]
I got error: "System.NotSupportedException: Standalone servers do not support transactions." 

It's happened on local machine when i try to debug code.  I would like to use the same code, without rewriting it, just set some debug flag. I notice that it can be easly fixed with modifications of Transaction class like this:

`

using MongoDB.Driver;
using System;
using System.Threading;
using System.Threading.Tasks;
using MongoDB.Entities;

namespace 
{

    public class APITransaction : DBContext, IDisposable
    {

        public APITransaction(string database = default, ClientSessionOptions options = null, ModifiedBy modifiedBy = null)
        {

            if (!emulateTransactions)
            {
                Session = DB.Database(database).Client.StartSession(options);
                Session.StartTransaction();
            }
            ModifiedBy = modifiedBy == null ? new ModifiedBy() : modifiedBy;
        }
        
        public Task CommitAllAsync(CancellationToken cancellation = default)
        {
            if (emulateTransactions) return Task.CompletedTask;
            return CommitAsync(cancellation);
        }

        #region IDisposable Support

        private bool disposedValue;

        protected virtual void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                    Session?.Dispose();
                }

                disposedValue = true;
            }
        }

        public void Dispose()
        {
            Dispose(true);
        }

        #endregion        
    }
}

`

**Comment by dj-nitehawk** [comment]
you just need to convert your local mongo server to a single-node replicaset as instructed [here](https://docs.mongodb.com/manual/tutorial/deploy-replica-set-for-testing/) because it is a requirement in mongodb to have a replicaset with at least 1 member to perform transactions.

after you convert your server, the same code will work fine without any need for modification.

typically the following is all you need to do to setup a single-node replicaset:
1. shutdown the mongodb service.
2. update the mongod.conf and add the replicaset setting. here's an [example](https://github.com/dj-nitehawk/MongoDB.Entities/blob/master/MongoDB.Entities/mongod.cfg)
3. start the mongodb service.
4. enter the mongo shell (or mongosh) and execute the command `rs.initiate()`

now you have a single-node replicaset for local development.

**Comment by rzer** [comment]
Thanks for your advice!
