### ISSUE TITLE
new attribute for always including specific properties when projecting with DB.Find<T>()

### ISSUE THREAD

**Issue by bobbyangers** [dj-nitehawk/MongoDB.Entities#116]
It would be very convenient to automatically include fields marked with **BsonRequired** when fetching records, 

for example:
 

    public sealed class Staff : Entity
    {
        [BsonRequired]
        public string Email { get; set; }

        [BsonRequired]
        public string DisplayName { get; set; }

        public string PhoneNumber { get; set; }
    }

Should return **Email** and **DisplayName** when using this:

`  var staff1 = await DB.Find<Staff>().Project(p => p.Include(_ => _.PhoneNumber) )
                .OneAsync(request.ID, cancellationToken);
`

I do know, I could use a different projection which does not contain the "required" fields,  but sometime it's convenient to retrieve partial records, and not have to specify all "required" fields explicitly.

**Comment by dj-nitehawk** [comment]
okay... sounds like a nice feature to have...
so to confirm... whatever the projection is you want the props that are marked with `[BsonRequired]` to be always included in the final result. is that right?
in which case, i will add a new attribute called `[AlwaysInclude]` which conveys better meaning than `BsonRequired` which is supposed to simply throw exceptions if the fields are not there at time deserialization. you will be however be able to use them together.

it will ofcourse incur some performance penalty due to reflection use. will investigate what can be done...

thanks for the suggestion.

**Comment by bobbyangers** [comment]
> okay... sounds like a nice feature to have...
> so to confirm... whatever the projection is you want the props that are marked with `[BsonRequired]` to be always included in the final result. is that right?
> in which case, i will add a new attribute called `[AlwaysInclude]` which conveys better meaning than `BsonRequired` which is supposed to simply throw exceptions if the fields are not there at the time of deserialization. you will be however be able to use them together.
> 
> it will ofcourse incur some performance penalty due to reflection use. will investigate what can be done...
> 
> thanks for the suggestion.
> 
> PS: ideally you'd wanna project to a DTO type which only has the exact properties your client application needs. such as:

Yes that the usual case,  but sometime the Entity is large and want to retrieve only a few properties for checking values and avoid loading the whole thing.  I encountered this issue while trying to load one property of the entity, and did not specify the three "required" properties; by "alwaysInclude" these properties, leaves the code cleaner.

**Comment by dj-nitehawk** [comment]
i think the solution to your problem is to simply not use `[BsonRequired]`. and use a projection like so:
```csharp
DB.Find<Staff>()
  .MatchID("xxxx")
  .Project(s => new Staff { PhoneNumber = s.PhoneNumber })
  .ExecuteSingleAsync();
```
i.e. if you want to retrieve partial entities, you should not use `[BsonRequired]` attribute supplied by the official driver.
`[BsonRequired]` is only useful if you wanna throw deserialization errors when the data returned by the database doesn't include those properties/fields. `[BsonRequired]` does not validate null/default values when entities are being serialized/persisted.

**Comment by dj-nitehawk** [comment]
ok... ended up going a different route than adding a new `[AlwaysInclude]` attribute.
you can now use `[BsonRequired]` together with `.IncludeRequiredProps()` method to get the desired effect.
```csharp
DB.Find<Staff>()
  .MatchID("xxxx")
  .Project(s => new Staff { PhoneNumber = s.PhoneNumber })
  .IncludeRequiredProps() //calling this method will add all properties decored with BsonRequired to the projection
  .ExecuteSingleAsync();
```
upgrade to v20.24 to try it out
