### ISSUE TITLE
IEntity to be of type ObjectID

### ISSUE THREAD

**Issue by Muchaszewski** [dj-nitehawk/MongoDB.Entities#126]
Knowing that the Idea for MongoDB.Entities are to "simplify" the default behavior of MongoDB.Driver, but being conscious about memory footprint, I would suggest having additional IEntity<T> or any other construct, where we can fall back to memory-optimized ObjectID for ID field and GenerateNewID method instead of a string.

ObjectID is a wrapper for 3 ints = (3 * 4 bytes) =12 bytes
String of ObjectID eg: "507f1f77bcf86cd799439011" = (24 * 2 bytes) = 48 bytes

Seems insignificant but in real-life application, it adds up in our application to 1.5MB per user times 15 000 requests we process per second is not insignificant ~2.0GB of additional memory that we need to process client requests

**Comment by dj-nitehawk** [comment]
the 36 additional bytes was the price i decided to pay for the feature set/ convenience back in the early stages of the library. 
unfortunately it is not easily changeable now without angering existing consumers of the library.

however, we do have a major rewrite in the works, maybe we'll try to figure something out. no gurantees though.

@ahmednfwela any ideas on how we could possibly support this? maybe with a generic type `Id<T>` where `T` can be ObjectId/String/Guid/Int whatever.

**Comment by ahmednfwela** [comment]
I actually thought about this before, especially since i was migrating an existing database where all my ids where `ObjectId`.
in times like this is where you wish the language supported mixins or union types, so we could just pass anything to it and let the serializer worry about it.

BUT since we don't, we have to tackle this differently
my approach:
```cs
/// <summary>
/// The contract for Entity classes
/// </summary>
public interface IEntity : IEntity<string>
{
   
}

/// <summary>
/// The contract for Entity classes
/// </summary>
public interface IEntity<TId> where TId : IComparable<TId>, IEquatable<TId>
{
    /// <summary>
    /// The ID property for this entity type.
    /// <para>IMPORTANT: make sure to decorate this property with the [BsonId] attribute when implementing this interface</para>
    /// </summary>
    TId? ID { get; set; }

    /// <summary>
    /// Generate and return a new ID string from this method. It will be used when saving new entities that don't have their ID set. 
    /// That is, if an entity has a null ID, this method will be called for getting a new ID value. 
    /// If you're not doing custom ID generation, simply do <c>return ObjectId.GenerateNewId().ToString()</c>
    /// </summary>
    TId GenerateNewID();
}
```

this would require adding a generic parameter TId to existing methods and classes, which can be done without breaking anything

BUT then you face another problem, what if we had multiple ids ?
e.g. in `JoinRecord`
```cs
/// <summary>
/// Represents a parent-child relationship between two entities.
/// <para>TIP: The ParentID and ChildID switches around for many-to-many relationships depending on the side of the relationship you're accessing.</para>
/// </summary>
public class JoinRecord : Entity
{
    /// <summary>
    /// The ID of the parent IEntity for both one-to-many and the owner side of many-to-many relationships.
    /// </summary>
    [AsObjectId]
    public string ParentID { get; set; } = null!;

    /// <summary>
    /// The ID of the child IEntity in one-to-many relationships and the ID of the inverse side IEntity in many-to-many relationships.
    /// </summary>
    [AsObjectId]
    public string ChildID { get; set; } = null!;
}
```

we would need to provide a special kind of id that gets ignored during serialization/deserialization, but can target all ids at once, say, in Find.
and then I remembered `ValueTuple`
```cs
public class MultipleIdEntity : IEntity<ValueTuple<Guid, ObjectId>>
{
    public (Guid, ObjectId) ID
    {
        get => (Id1, Id2);
        set => (Id1, Id2) = value;
    }
    public Guid Id1 { get; set; }
    public ObjectId Id2 { get; set; }
    public (Guid, ObjectId) GenerateNewID() => (Guid.NewGuid(), ObjectId.GenerateNewId());
}
```
this requires us to write some sort of magic serializer that maps ID to Id1,Id2 back and forth

**Comment by ahmednfwela** [comment]
or maybe this 
```cs
public class MultipleIdEntity : IEntity<ValueTuple<Guid, ObjectId>>
{
    public (Guid, ObjectId) ID { get; set; }
    [BsonIgnore]
    public Guid Id1
    {
        get => ID.Item1;
        set => ID = (value, ID.Item2);
    }
    [BsonIgnore]
    public ObjectId Id2
    {
        get => ID.Item2;
        set => ID = (ID.Item1, value);
    }
    public (Guid, ObjectId) GenerateNewID() => (Guid.NewGuid(), ObjectId.GenerateNewId());
}
```
which would require changing the queries to target `ID.Item1` and `ID.Item2` instead

**Comment by dj-nitehawk** [comment]
@ahmednfwela we could simplify by not allowing composite ids for the primary key.
and yeah `JoinRecord` does need to support TId for both ParentID/ChildID interchangeably which complicates things a bit.

@Muchaszewski come to think of it, doesn't the asp.net json serializer always need to allocate 48 bytes when reading/deserializing an objectid string from the json request anyway? because your http client is sending the `ID` as a string right? or are you planning to use a custom json serializer that will parse the bytes from the request directly to a ObjectId struct?

or am i completely off base ;-)

**Comment by ahmednfwela** [comment]
@dj-nitehawk yes, but with asp.net you can choose to serialize ObjectId as 3 numbers, or as a string
I think he is talking about the overhead of extra serialization from MongoDB

**Comment by Muchaszewski** [comment]
@dj-nitehawk 
I don't know the details but heap allocation during deserialization doesn't matter as much (even if it's using string internally, which I doubt). So downloading data from MongoDB where ObjectID is a string doesn't matter.

The part that is critical is store since we are caching a lot of data that are mostly ObjectIDs, and when stored they are the bulk of memory footprint we see in the application right now.

**Comment by dj-nitehawk** [comment]
no worries... with @ahmednfwela's refactor, you will be able to specify the type of the primary key to whatever you want.
it would take some time to come out though since we need to document and test properly for some time (at least a couple of months) before we release it in to the wild.

**Comment by dj-nitehawk** [comment]
implemented by `v23` release
