### ISSUE TITLE
I got error like IQuryable not implimented

### ISSUE THREAD

**Issue by JigarPrajpati** [dj-nitehawk/MongoDB.Entities#127]
I using .net core 6, and implimented your library, when i run this it given me error.

![image](https://user-images.githubusercontent.com/91531559/141684451-f494ddfb-1297-4b03-b346-e370d82b21b4.png)

error
![image](https://user-images.githubusercontent.com/91531559/141684458-bbbaf918-ce9c-425d-96e2-f06ac53d4c50.png)

**Comment by dj-nitehawk** [comment]
at which line number is the exception thrown? 
line 1 or line 5 of the screenshot?

**Comment by dj-nitehawk** [comment]
also, can you show me your using statements for this controller class?

**Comment by dj-nitehawk** [comment]
the exception seems to be thrown by entity framework. not mongodb driver. are you using entity framework in this project?

**Comment by JigarPrajpati** [comment]
I got error at line no .1
second yes i use entity frameowkr but i don't reference anything of entity frameowrk here. because entity frameowrk is also used at another class for SQL query.

![image](https://user-images.githubusercontent.com/91531559/141687340-770c5e0a-b10b-4dd9-a9df-41ca65939e8d.png)

Dear sir please see this image, Queryable are referenced by Mongo, so i don't think this error should be come.

**Comment by bobbyangers** [comment]
Hi gemtlemen.

It is likely because of using « mixin ».  You should review the your usings.

--Robert Angers
m:514-557-8074

Sent from my iPhone

On Nov 14, 2021, at 10:24, JigarPrajpati ***@***.***> wrote:

﻿

I got error at line no .1
second yes i use entity frameowkr but i don't reference anything of entity frameowrk here. because entity frameowrk is also used at another class for SQL query.

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F91531559%2F141687340-770c5e0a-b10b-4dd9-a9df-41ca65939e8d.png&data=04%7C01%7C%7C6b751e1873d54870a25008d9a782e1ba%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637725002834613610%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E92WYaafeHMHcghpLYisbhAO1tVGmPEvEeYdWKiUakc%3D&reserved=0>

Dear sir please see this image, Queryable are referenced by Mongo, so i don't think this error should be come.

**Comment by JigarPrajpati** [comment]
He i found the error, i using ToListAsync from enity framework.
Thanks,.
