### ISSUE TITLE
Where can i add all indexes in startup in Dev envionment or is it need all time when startup .net core

### ISSUE THREAD

**Issue by JigarPrajpati** [dj-nitehawk/MongoDB.Entities#128]
![image](https://user-images.githubusercontent.com/91531559/141705829-7ba7f4bc-9924-4736-9f9c-ad8b654ef7d2.png)

is it always requried Task.Run() ? can't be use directly  like this?
![image](https://user-images.githubusercontent.com/91531559/141705859-ac4dc345-ff22-4c66-992e-5ea7b74665c3.png)

Also second question is it fine to declare all indexes in static constructors, i know you said it will ignore by server, but it will go to server all the time, so it might make performance issue in future right?

Also want to know how can i use such things via LINQ?
![image](https://user-images.githubusercontent.com/91531559/141706086-4d59e570-319c-4581-98ac-08eee6eea63c.png)

**Comment by dj-nitehawk** [comment]
- all of your environments (dev/production) should have the exact same indexes.
- if your runtime's startup supports async, there's no need to do `Task.Run`. for example in .net 6
- static constructors are only ever run once per app cycle. so it is fine. only reason why you wouldn't wanna put your index creations in static ctor is because any exceptions thrown by index creation will not be caught because they're not being awaited due to lack of async/await support in static ctors. what i usually do is when designing/testing indexes, i use `.GetAwaiter().GetResult()` and remove it when deploying. alternatively you can put all of your index creations in one massive `IndexSetup.cs` class and call that in your app startup. choice is yours.
- fuzzy text matching is not available via linq. there's really no point because fuzzy search only takes 1 argument.

hope that answers your questions. if something needs further clarification, let me know...

**Comment by JigarPrajpati** [comment]
Love you, thanks 💓
