### ISSUE TITLE
Cannot deserialize a FuzzyString value from a [String]

### ISSUE THREAD

**Issue by JigarPrajpati** [dj-nitehawk/MongoDB.Entities#130]
I mostly using dynamic projection and sometime oData too, but when we use FuzzyString it always throw error when use something like this
![image](https://user-images.githubusercontent.com/91531559/141761152-39f24142-e84e-421c-a259-860a32d018d6.png)
![image](https://user-images.githubusercontent.com/91531559/141761190-1d1420ea-273f-4162-ab2d-b221654c0c4a.png)

Error appear when using Dynamic Select or with OData

![image](https://user-images.githubusercontent.com/91531559/141761112-d9c3de82-2ee4-41f2-a6b6-dd40d977c59e.png)

**Comment by dj-nitehawk** [comment]
it's not a bug. 
asp.net json serializer doesn't know how to deserialize the type `FuzzyString`.
you have two options:
1. use a dto and project your results to the corresponding dto type like this:
```csharp
class ProductSearchResult
{
    public string Id { get; set; }
    public string Name { get; set; }
    public decimal Price { get; set; }
}

public class Product : Entity
{
    public FuzzyString Name { get; set; }
    public decimal ItemPrice { get; set; }
}

var searchResults = await DB
    .Queryable<Product>()
    .Select(p => new ProductSearchResult
    {
        Id = p.ID,
        Name = p.Name.Value,
        Price = p.ItemPrice
    })
    .ToListAsync();
```
2. teach asp net serializer how to deserialize fuzzystring. but i'd recommend against this because it's never a good idea to expose your data entities to your api clients. always use dtos and send only the exact fields that are needed.

**Comment by dj-nitehawk** [comment]
on a sidenote, since you're using minimal api, you might be interested in this library as well: https://fast-endpoints.com/

**Comment by dj-nitehawk** [comment]
wait wait wait....
i think my above reply may be wrong...
this is most likely happenning because one of the mongo documents in your database has a `string` value for the `Name` field instead of a `document` that looks like this:

```
{
  "Name": {
      "Value": "...",
      "Hash": "..."
  }
}
```

all fuzzystring properties/fields in the db should be the above format for it to work.

find that document and re-save it. that should fix the issue.

**Comment by dj-nitehawk** [comment]
also just noticed another thing. with asp.net 6, `Task.Run` is not needed. just do something like this:
```csharp
public class Product : Entity
{
    static Product()
    {
#if DEBUG
        DB.Index<Product>()
          .Key(p => p.Name, KeyType.Text)
          .CreateAsync()
          .GetAwaiter()
          .GetResult();
#endif
        DB.Index<Product>()
          .Key(p => p.Name, KeyType.Text)
          .CreateAsync();
    }

    public FuzzyString Name { get; set; }
}
```
which basically means, during debugging your index creation will block the current thread and throw any exceptions that will occur. during production, it will be executed in the background and no blocking will occur.

**Comment by jigarprajapatieastern** [comment]
Dear sir what you means by this?
![image](https://user-images.githubusercontent.com/82803338/142172764-dd127233-8d09-4ae1-8f03-1fedee8815a8.png)

i think this is automatically done by FuzzyString, i don't need to do anything except annonymous property right? so what meaning of this comment, i didn't get idea sir. 

Thanks you gentleman.

**Comment by dj-nitehawk** [comment]
it is done automatically for you if you have saved all the records using the library. 
if some of the records are saved externally (or you've saved some records with a different schema yourself) to the db which could result in mixed schema in the db such as:
```
[
  {
    "Name": {
        "Value": "Eckhart Tolle",
        "Hash": "AKRT TL"
    }
  },
  {
    "Name": "Charles Dickens"
  }  
]
```
the library will be able to retrieve/deserialize the first document, but will fail to deserialize the second document because the type of the `Name` field is `string`. It should be a `bsondocument` like in the first one for FuzzyString properties.

if you run the following [mongo query](https://mongoplayground.net/p/490yF2QZ14c) on your product collection, it will show you which records have the incorrect schema:
```
db.Product.find({ Name: { $type: "string" } } )
```

hope it's clear now.
