### ISSUE TITLE
Does making indexes do any server call?

### ISSUE THREAD

**Issue by JigarPrajpati** [dj-nitehawk/MongoDB.Entities#147]
![image](https://user-images.githubusercontent.com/91531559/146298304-430e3eeb-a6ce-4b1d-980f-da8b631d1b86.png)

i do something in mongoDB to create indexes, so is it make any server call or something to verify/do/check index ? because all time the application run it need at least one time require to call to work indexes, so if it make any server call for each table for each index it might not performance full right?

**Comment by dj-nitehawk** [comment]
if the index on the server is an exact match to the index you have in you c# code, then there won't be any issue.

if the server index is different, then a new index will be created to match your c# index when the app starts up. mongo server will decide which index to use by it's own rules if there are duplicated indexes. 

so, in order to prevent duplicate/redundant indexes, try not to do things manually on the server and let your c# app take care of index creation.

if an index needs to be updated, use a migration to drop and then recreate the index.

read more on this matter here: https://mongodb-entities.com/wiki/Schema-Changes.html#indexes
