### ISSUE TITLE
How to match on single element

### ISSUE THREAD

**Issue by jigarprajapatieastern** [dj-nitehawk/MongoDB.Entities#159]
I want to filter single element and update, how can i do it.
![image](https://user-images.githubusercontent.com/82803338/171008083-b180f974-0ebc-4b38-981e-cfe57e31aaa1.png)

here Dish have ID and i want to filter based on it and update, how can i do it please help me bro

![image](https://user-images.githubusercontent.com/82803338/171008047-70923aa5-9420-4c46-8d3f-6dec3ed452f9.png)

**Comment by dj-nitehawk** [comment]
instead of screenshots, pls post code that I can easily copy/paste in to an ide and run. otherwise it takes too much of my time to provide help with stuff directly not related to the library like this. 

see the example here: https://mongodb-entities.com/wiki/Entities-Update.html#update-with-builder-methods

do a Modify(x=>x.Set(...)) to update an embedded object. 

I'm not near a computer atm. if you need further help pls post code which I can correct and post back when I get to a computer.
