### ISSUE TITLE
Need confirmation over ID value

### ISSUE THREAD

**Issue by JigarPrajpati** [dj-nitehawk/MongoDB.Entities#164]
I seen that the entity's auto generate ID value's first part is same and last part with sequence number. so i have 2,000 rider around the whole india, and all rider save entry for different banks speedly, so only adding sequence number will not conflict with same record in future?

```
62a82b2b522f337f862da070
62a82b2b522f337f862da071
62a82b2b522f337f862da072
62a82b2b522f337f862da073
62a82b2b522f337f862da074
```

**Comment by dj-nitehawk** [comment]
you can find the answer to this here:
https://mongodb-entities.com/wiki/Entities.html#customizing-the-id-format

in the yellow warning section

**Comment by JigarPrajpati** [comment]
Dear dj-nitehawk i understand it, but my concern is different in this case, that i get only new objectID from the server via API and save into bootstrap popup's hidden id field to do some front end (client side) processing, once front end(client side) processing complete i save record with that hidden field ID, so is there any chance that while frontend processing entering by user, server generate same to same objectId for another user? otherwise it will cause biggest issue.

as per my understanding i think ObjectId.GenerateNewId().ToString(); is generating new ID from memory not from MongoDB database, than it can be biggest issue.

**Comment by dj-nitehawk** [comment]
if you read the doc page above it says:
> the only way it could ever generate a duplicate ID is if more than 16 million entities are created at the exact moment on the exact computer with the exact same process.

objectid generation is done by the c# driver, not the database.

**Comment by paolobriones** [comment]
I had a similar issue with mongodb ObjectID, but I think my situation was a little bit different.

My system is multi-tennant and since ObjectID is somewhat sequential and there is a risk of the user manipulating the ids sent from the browser (although i had a lot of security checking on the server side) but just to make sure, i used GUID as my custom ID, using Guid.NewGuid().ToString("n") to remove the dashes. This feature works really well, although i have had problems with FileEntity having to use the normal ObjectID instead of GUID 

I do recognize @dj-nitehawk's warnings on the documentation that this might cause ID collisions, but thru my testing, i have not encountered this at all.

@JigarPrajpati this might be useful to you, sounds like you are also building a multi-tennant system and are sending raw ids to your frontend
