### ISSUE TITLE
DB.GetInstance() should return null instead of throwing an exception

### ISSUE THREAD

**Issue by paolobriones** [dj-nitehawk/MongoDB.Entities#17]
With the ability to create new instances of DB, instead of throwing an exception when the database is not yet initialized in the "instances" dictionary, shouldn't the API just return null so that the caller can initialize instead of using a try..catch to recover? Or maybe initialize automatically when calling DB.GetInstance()?

My use case is that my project has to support multiple MongoDB databases on different clusters; to simplify and centralize all my database operations, I created repository classes that automatically handle this.

**Comment by dj-nitehawk** [comment]
firstly, the getinstance method is not able to automatically initialize connections because it doesn't know the connection details. that's the job of `new DB()` method.

and i think it's a bad idea to return null from the getinstance method because of the potential to cause null reference exceptions.

besides, the developer is expected (recommended) to initialize all connections/dbs during the startup of the application (or the instantiation of the repo classes) to keep things organized and clear.

getinstance's sole responsibility should be to return the instance or crap out if the developer has forgotten to initialize an instance at the appropriate place.

hope you see my point of view.

**Comment by Seyden** [comment]
Well you can't initialize the DB in a azure function i think, at least i didnt find a Startup Class where you can initialize things.

I got the same problem like the issue owner, in my azure time trigger function, i use the DB to update things, but DB.GetInstance() returning a exception feels chunky. And if i create it in the first ever called TimeTrigger, it will be there, but thats not a way to initiate it.

**Comment by dj-nitehawk** [comment]
ok, i believe i have the solution for azure functions with the latest release v8.11.1

now you can call `new DB()` as many times as you want and it won't throw an exception.

so, you can now new up DB instances from anywhere and for however many times as you wish.
no new actual db connections will be made if your function is running on the same server and the app context hasn't been destroyed/recycled (if i understand how azure functions work).

`DB.GetInstance()` will still throw if you've forgotten to initialize the connection for a given db, but you don't need to rely on it anymore due to the above mentioned change.

@paolobriones i hope this will help you too.

let me know what you guys think...

cheers!
