### ISSUE TITLE
ChildrenCount is counting dead items

### ISSUE THREAD

**Issue by Seyden** [dj-nitehawk/MongoDB.Entities#19]
Hey, i just found a bug (i think its a bug).

If you add a relational item to a Many Collection and you go inside the database and delete it manually (without deleting the reference in the relation table which gets auto created), ChildrenCount will count the objects based on the relational table, it doesnt matter if the real document doesnt even exist anymore.

Greetings

**Comment by dj-nitehawk** [comment]
don't think this can be considered a bug but a limitation i suppose. when relationships are managed by the library and something else changes the database, the library is not able to automagically figure out that a referenced entity was deleted. so in order to avoid the problem i can recommend two things:

1. don't delete referenced entities manually
2. if deleting manually, also make sure to delete the join record from the join collection

alternatively we could run a background thread to validate and delete every join record that are no longer valid. i'm reluctant to do something like that due to the sheer wastage of cpu/io power and the inability to make such a process reflect correct results due to the delay involved when dealing with millions of records.

i'm open to suggestions of better approaches though...

**Comment by Seyden** [comment]
The problem is, the manual thing i mentioned was just a example, i had them created over a azure function, 10.000 in total and somehow in the database there were 10001, i looked for the error and as it seemed, he created one more in a relation but didn't create the object itself.

Its all running over a transaction.. so i dont know what caused that.. but also having him count dead items is kinda meh..

```
using var tn = new Transaction();

for (var i = 0; i < 500; ++i)
{
    ISBN isbn = new ISBN
    {
        Number = "Test",
        Status = IsbnStatus.StatusNew,
        Count =i,
        IsbnGroup = isbnGroup.ToReference()
    };
    await tn.SaveAsync(isbn);

    await isbnGroup.Numbers.AddAsync(isbn);
    await tn.SaveAsync(isbnGroup);
}

await tn.CommitAsync();
```

That was the code.. i guess when it crashes and if he can't execute CommitAsync, he will delete everything again right?

**Comment by Seyden** [comment]
For what exactly do you even need a extra table? Wouldn't it be enough to store the ObjectIds inside the original object? Like you do it with One<T>, instead of having only one ObjectId, storing a collection of ObjectIds and then really counting the original objects instead of just counting the connections, which could be broken already.

**Comment by dj-nitehawk** [comment]
aha... you forgot to pass the session to the .AddSync method as explained here: https://github.com/dj-nitehawk/MongoDB.Entities/wiki/06.-Transactions#relationship-manipulation

**Comment by dj-nitehawk** [comment]
> For what exactly do you even need a extra table? Wouldn't it be enough to store the ObjectIds inside the original object? 

i can't remember the exact reasons why i went the "join collection" route but off the top of my head, there's a limit to how big a record can get (16mb) in mongodb. embedding millions of IDs could result in reaching that limit.

**Comment by Seyden** [comment]
> > For what exactly do you even need a extra table? Wouldn't it be enough to store the ObjectIds inside the original object?
> 
> i can't remember the exact reasons why i went the "join collection" route but off the top of my head, there's a limit to how big a record can get (16mb) in mongodb. embedding millions of IDs could result in reaching that limit.

Oh i see, makes sense then..



> aha... you forgot to pass the session to the .AddSync method as explained here: https://github.com/dj-nitehawk/MongoDB.Entities/wiki/06.-Transactions#relationship-manipulation

Thanks i will try that out and hope that this issue will never occur anymore.
