### ISSUE TITLE
fulltext search again - case sensitive and insert on duplicate

### ISSUE THREAD

**Issue by schorges** [dj-nitehawk/MongoDB.Entities#22]
i had a problem with fulltext search (textbox with keydown event and
search on all typed chars)

after long searching i found a solution, 
but this is a slow version. on 
DB.SearchText -< only case sensitve and the full word will search

my way:

   ```

 //regex ? not work will result all:
                //var list = DB.Find<MyTestItem>()
                //    .MatchExpression("{ '$regex':'"+searchtext+"', '$options' : 'i'} " )                
                //    .Execute();

//work but is this the right way?
var list = DB.Queryable<MyTestItem>()
                          .Where(s =>
                                 s.name.ToLower().Contains(searchtext) )                             
                          .ToList();
```

my question no2 ist why can i insert and handle a string only once in db?
how does the insert command look?

`.Option(o => o.Unique = true)`

or this, but i think its not perforant?
```csharp
if (!DB.Find<MyTestItem>().Many(a => a.name == textBoxNameInsert.Text.Trim()).Exists(a => a.name == textBoxNameInsert.Text.Trim()))
            {
                var newItm = new MyTestItem()
                {
                    name = textBoxNameInsert.Text.Trim(),
                    vorname = textBoxNameInsert2.Text.Trim(),
                };
                newItm.Save();
                textBox1.AppendText("NEU angelget " + textBoxNameInsert.Text.Trim() + Environment.NewLine);
                loadListbox();
            }
            else
            {
                textBox1.AppendText("Schon vorhanden" + textBoxNameInsert.Text.Trim() + Environment.NewLine);
            }
```

_Originally posted by @schorges in https://github.com/dj-nitehawk/MongoDB.Entities/issues/21#issuecomment-570791588_

**Comment by dj-nitehawk** [comment]
> DB.SearchText -< only case sensitve and the full word will search

this method is case insensitive by default. you can make it case sentitive by changing the 2nd parameter to `true`.

as explained in #21 mongodb does not do partial word matching with text indexes and you need to resort to regex matching with the linq `.Contains()` method.

> my question no2 ist why can i insert and handle a string only once in db?

sorry, i can't understand what your requiremet here is. i'm assuming you want to only create/insert a new record if no entities with the same name exists in the db right?

if so, the performant way would be to create a unique index on the `name` field. mongodb will throw an exception when you're trying to create a duplicate entity with an existing name.

alternative would be the following. it would be more performant than your code because it won't retrieve a whole bunch of entities and check for the existence of name on the clientside.

```csharp
    if(DB.Queryable<MyTestItem>().Count(i => i.name == "xxxxxx") == 0)
    {
        // save a new item here
    }
```

**Comment by schorges** [comment]
Top!

this work now for me on a blazor app:
`if(DB.Queryable<MyTestItem>().Count(i => i.name == "xxxxxx") == 0)
    {
        // save a new item here
    }`

and the `.Contains()` method without case sensitve to all chars

`var list = DB.Queryable<MyTestItem>()
                          .Where(s =>
                                 s.name.ToLower().Contains(searchtext) || 
                                 s.vorname.ToLower().Contains(searchtext))                             
                          .ToList();`
