### ISSUE TITLE
Provide documentation of database migrations for seperate project using dotnet commands

### ISSUE THREAD

**Issue by arifjmamun** [dj-nitehawk/MongoDB.Entities#25]
I have multiple projects under a solution and one of them has **MongoDB.Entities** models. In your documentation, you described creating the migration class, but don't have any idea where to put them and how to migrate them. Is there any way to generate migration class by executing the command as the dotnet ef tool has?

**Comment by dj-nitehawk** [comment]
can you explain your requirement a bit more please?

**Comment by dj-nitehawk** [comment]
you can put the migration classes in any project. but i'd recommend you put them in the same project as the entity models. or even any project that references `MongoDB.Entities` namespace. it's really up to you.

the important thing is to execute `DB.Migrate()` command at the startup of your application. execute it before any data access is done from your app. if your app is an asp.net app, then it would be inside the startup.cs file right after the DB initialization command.

the migrate command will discover all migration classes from all of your projects by default and execute them in order if they haven't been executed before.

you can specify which project to load the migration classes from by doing this:
```csharp
DB.Migrate<SomeClass>();
```
instead of `SomeClass` you can enter any class from the same project as your migration classes. doesn't even have to be a migration class.

let me know if you need further clarification...

**Comment by arifjmamun** [comment]
It would be great if we can use dotnet-ef tool commands to generate migrations based on changes.

**Comment by dj-nitehawk** [comment]
well, this library nor mongodb has anything to do with entity-framework. so it's best to let go of ef-tools/commands mentality when working with mongodb.

if doing db migrations on app startup doesn't appeal to you and you need to run migrations from commandline, you can simply make a console app and make your own command. 

in that console app, simply reference MongoDB.Entities library and also add a reference to the project where migration classes reside. then simply execute DB.Migrate(). easy...

but there's no need for it imho. i've been doing automated migrations with this library for a couple of sizeable (n-tier) projects of mine and everthings good. it even works nicely multiple environments such as dev > staging > uat > production. i don't need to run any commands manually. on app startup the database is transformed to match the current schema of my entity classes.
