### ISSUE TITLE
QOL For save

### ISSUE THREAD

**Issue by ColonelBundy** [dj-nitehawk/MongoDB.Entities#28]
Consider this example:

```
var author = new Author { Name = "Eckhart Tolle" }
author.Save();
book.Author = author;
book.Save()
```

Wouldn't it be better to detect author is new and not persisted in the ```book.Save()``` without having to call ```author.Save()```

I'm thinking the ObjectId has not been set for author so it should be fairly easy to detect.

Thoughts?

**Comment by dj-nitehawk** [comment]
i think it's a bad idea for the library to do that automatically due to cases such as:

say the developer wants to just embed the author without actually saving it.
```csharp
var author = new Author { Name = "Eckhart Tolle" }
book.Author = author;
book.Save()
```
this will embed the author in the book with a `null` id. which is the expected behavior. if the library saves the author to the collection without the developer explicitly saying so, that's a bug. now there's an unwanted author entity in the collection.

and for referenced relationships, we could assume the developer intended to save the author to the db if they wanted to reference that author from another entity like so:
```csharp
book.AuthorRef = author.ToReference();
```
but i feel it's good to keep the behavior consistent everywhere and let the developer train themselves in to explicitly saving entities.

hope you see my point of view :-)

**Comment by ColonelBundy** [comment]
Gotcha, could we possibly introduce another method for it as a compromise? For instance... ```book.SaveAll()``` ? 
In most cases I just feel like it's a lot of repetitive calls and people coming from entity framework would feel more at home, me included.

**Comment by dj-nitehawk** [comment]
it would also be bad from a performance perspective because I'd have to use reflection to loop through each and every property of the entity being saved to see which properties contain other entities that haven't been saved. I've seen classes that contain close to 100 properties. using reflection on a class like that would be a crime imho. also what happens to deeply nested unsaved entities? should the library auto save those too? 

you it's just an unnecessary complication from the perspective of the library. 

for referenced relationships however I'm willing to create an additional method for adding a related entity. something like `book.Authors.AddSaving(author)`
