### ISSUE TITLE
Clarification on where to put repository-style methods

### ISSUE THREAD

**Issue by paolobriones** [dj-nitehawk/MongoDB.Entities#4]
Being able to query the collection directly thru linq is pretty good, but i would also like to have pre-built methods that just return an entity list or a single entity based on parameters.

i.e.

`public List<Book> GetBooksWith5StarReviews(){  ...  }`

Should this be put directly on the entity class?

**Comment by dj-nitehawk** [comment]
if you're a fan of the repository pattern, you can create separate repos for your entities and encapsulate the DB class.

but i personally don't do that because:
1. this library is like a generic repo and there's no need to duplicate functionality
2. entity classes are mostly domain objects, so makes sense to put business logic in the entities.

here's an [example](https://github.com/dj-nitehawk/KiwilinkCRM/blob/52804985cc71ae3cb7a83e732202d7ee22669f37/Kiwilink-API/Models/Task.cs#L29) where i do that.

if it doesn't make sense to put a certain query/method on an entity class, then you can create separate service class. use services for larger projects for maintainability i suppose.

**Comment by paolobriones** [comment]
Noted, looks good

**Comment by dj-nitehawk** [comment]
hey, check out [this repo](https://github.com/dj-nitehawk/MongoWebApiStarter/) i created. this is the pattern/ architecture i use for medium to large scale web api projects. thought you might find this useful...
