### ISSUE TITLE
services.AddMongoDBEntities is very slow with atlas

### ISSUE THREAD

**Issue by BartRennes** [dj-nitehawk/MongoDB.Entities#42]
Dear, i'm starting with MongoDB.Entities under an asp.net core 3.1 site, i added in startup.cs the service like this:
services.AddMongoDBEntities(
                MongoClientSettings.FromConnectionString("mongodb+srv://xxxxx:xxxx-amkq1.mongodb.net/test?retryWrites=true&w=majority"),
                       "MyTEST");

My question is: Do you open the connection to DB when the service is added? Because the start is very very slow (over 8 seconds), is there something we can do to improve this? As the DB access is used only on some pages.

Note: i just start with MongoDB, your library seems very good with an easy access, good job ;)

Regards,
jc

**Comment by dj-nitehawk** [comment]
the atlas free tier is extremely slow. it's not suitable for any kind of production use. and yes, the first connection is opened on adding the service. see [here](https://github.com/dj-nitehawk/MongoDB.Entities/blob/d85b8479afb2580efaa45aa2ce222104ffa523a7/MongoDB.Entities/DB.cs#L58) in the source.

but the max delay i've seen is around 3 seconds for atlas. can you try with a local db and make sure it's the network that's the culprit?

or you can verify by simply try connecting using the official driver and getting a list of collection names. see how long that takes.

my assumption is it's gonna be the same network lag because this library also uses the official driver underneath.

**Comment by dj-nitehawk** [comment]
oh forgot to mention, you don't need to register with the services collection on startup. you can simply do the following:
```csharp
new DB(MongoClientSettings.FromConnectionString(
        "mongodb+srv://user:password@cluster.mongodb.net/DatabaseName"), 
        "DatabaseName");
```
you can place it anywhere in your app and as many times as you want.

**Comment by BartRennes** [comment]
Thank you for fast reply, yes the Atlas connection is very slow... Continue your great work.

Regards,
jc
