### ISSUE TITLE
Loosen IEntity requirement

### ISSUE THREAD

**Issue by molinch** [dj-nitehawk/MongoDB.Entities#48]
Would it be possible to loosen the IEntity requirement?
Maybe we could specify Id and ModifiedOn via attributes instead?
Also ModifiedOn could probably be optional?

It would allow having whatever name and structure for these, for example:
```c#
public class Book {
  [Id]
  public int Id { get; set; }
  public BookMetadata Metadata { get; set; }

  public class BookMetadata {
     [ModifiedOn]
     public DateTime ModifiedOn { get; set; }
  }
}
```

Btw is the ModifiedOn UTC based?

**Comment by dj-nitehawk** [comment]
hello...

the library has 66 references internally to the `ID` property. so it cannot be easily done without significant re-engineering and a performance penalty due to reflection use imho.

the `ModifiedOn` property is there to easily enable sorting by the modified date when doing queries. this is extensively being used in a lot of projects already. 

if you however don't want to store it  with your entities, you can implement your own entity base class like this:

```csharp
    public class EntityBase : IEntity
    {
        public string ID { get; set; }

        [Ignore]
        public DateTime ModifiedOn { get; set; }
    }

    public class Person : EntityBase
    {
        public string Name { get; set; }
    }

    static class Program
    {
        private static void Main()
        {
            new DB("test");

            new Person { Name = "john doe" }.Save();
        }
    }
```

mongodb always converts non-UTC datetimes to UTC when storing in the db, so yes if you set a local datetime on the `ModifiedOn` it will be converted to UTC after saving. on retrieving you will get back UTC also.

**Comment by molinch** [comment]
Reflection cost can be avoided, that requires IL emitting but it's not difficult.
Anyway I understand your point of view, thanks for replying.
