### ISSUE TITLE
Match on null array item

### ISSUE THREAD

**Issue by molinch** [dj-nitehawk/MongoDB.Entities#55]
Imagine you have the following document in the collection Game:
```js
{
  cells: [ null, null, { value: 'x' }, null ]
}
```

With Mongo syntax you can perform queries like: get documents where cell[1] is null
It would look like:
```js
db.getCollection('Game').find({'cells.1': { $type: 10 }})
```
For reference: https://docs.mongodb.com/manual/tutorial/query-for-null-fields/

Unfortunately if we write in C#:
```c#
db.Find().Match(g => g.Cells[1] == null)
```
I believe that it gets translated to:
```js
db.getCollection('Game').find({'cells.1': null})
```
Which will match any game document...

Is there a way to write the correct query? or at least to pass it as a raw string?

**Comment by dj-nitehawk** [comment]
you can run raw queries using the [string template](https://github.com/dj-nitehawk/MongoDB.Entities/wiki/13.-String-Templates) system or you can supply an [aggregation expression](https://github.com/dj-nitehawk/MongoDB.Entities/wiki/04.-Queries#find-by-aggregation-expression-expr) to the find command builder.

**Comment by molinch** [comment]
That's awesome support thanks a lot @dj-nitehawk

**Comment by dj-nitehawk** [comment]
looks like i missed the template overload on the updateandget class. i'll add that today.

as for the match method, all across the library, the behavior is the same which is you should only use it once. right now it won't complain and simply set the filter of the query to the last match. maybe i will add an exception so that if match is called more than once, it will throw informing the user not to do that.

because the need for calling match multiple times can be alleviated with something like this:
```csharp
            var filter1 = DB.Filter<Book>().Eq(b => b.Title,"one");
            var filter2 = DB.Filter<Book>().Gt(b => b.Price, 10);

            DB.Update<Book>()
              .Match(b => b.And(filter1, filter2))
              .Modify(b => b.Price, 12)
              .Execute();
```
to support the use of multiple matches you'd have to manually render and combine the raw filter definitions as there is no quick method for combining them in the official driver (afaik). it could get quite complicated depending on the type of filters. but you're welcome to have a crack at it. i've done something similar [here](https://github.com/dj-nitehawk/MongoDB.Entities/blob/ffdb05ad4d2c553e455ad36c1a6a800199d60e7e/MongoDB.Entities/Commands/Find.cs#L389).

if you can manage it, we can add a new method called `.AndMatch()` or `.MatchMulti()` indicating that it can be used many times. that way existing code won't break.

let me know your thoughts...

**Comment by dj-nitehawk** [comment]
actually nevermind the above. just figured out an easy way to combine filters. i'll add the ability to call match multiple times as a breaking change. though i doubt it would break much as 95% users are already aware of the current behavior and they probably don't have multiple match statements in their code.

**Comment by molinch** [comment]
That would be awesome, and if we can combine the Match(Template) with the Match(expression) that would really rock!

**Comment by molinch** [comment]
@dj-nitehawk if you could do a nuget release that would be even more awesome :)

**Comment by dj-nitehawk** [comment]
yep all done. pushed v13.2.1 to nuget. might take a few minutes to show up.
thanks for the PR.
