### ISSUE TITLE
Multi DB got broken with latest release

### ISSUE THREAD

**Issue by molinch** [dj-nitehawk/MongoDB.Entities#58]
It's very simple to test:
- Two connections to two different databases having similar collections (same types)
- 2 unit tests, each writes into a different db
You end up with data only in one of the db

I'm reviewing the code from last commits, it could have been introduced with the caching

**Comment by molinch** [comment]
I confirm that it's because of the caching :)

**Comment by dj-nitehawk** [comment]
did it use to work before? 
i think this is a known (but not obvious) limitation. as placing the Database attribute on an entity ties that entity to a single database. so it's a given that you can't store a single entity in two dbs. querying would also be problematic if an entity is stored in two collections in two dbs. I think the code is working correctly now enforcing the restriction. 

 need to clarify this point in the wiki more.

**Comment by molinch** [comment]
It definitely worked before you added the caching

**Comment by dj-nitehawk** [comment]
have a look at the wiki page for multi dbs. it's a requirement to decorate entities you wanna store in a non-default db with the attribute. 

I think it was working before due to the way the DB instance was passing the DB down the line. now it's always reading which DB to store an entity using the attribute. if no attribute is present then it gets saved to the first/default DB. this is the behavior mentioned in the wiki. 

guess you were using it in a non standard way before. 

I really don't wanna lose the caching feature at this point. 

also if you store the same type in two dbs then querying will only give your half the records. it's not gonna automatically query both and give you the correct/totals.

**Comment by molinch** [comment]
> also if you store the same type in two dbs then querying will only give your half the records. it's not gonna automatically query both and give you the correct/totals.

Yes, I was aware of that

I understand if you don't want to change it, however almost all ORMs that exists don't work like that.
It is usually not the entity which is coupled to a given database. But the opposite the db context which has entities.

For example with EF Core, it is the database context which is used in order to persist given entities.
Hence you can definitely have the same entity being used in two contexts.

**Comment by dj-nitehawk** [comment]
yeah mongo is a very different beast and requires letting go of the EF mentality. 

this way we have no real need for a db context. everything can be done with the DB class static methods or the extension methods on the entities. 

the db instances/ contexts are there for just eye candy I suppose 😜

also if we are going to supper this use case, how are we going to solve the querying issue? 

so I think it's best to leave it as is. 

if you have ideas I'm all ears. 

btw thanks for all the feedback. totally appreciate it. 

cheers!

**Comment by dj-nitehawk** [comment]
i updated the wiki page to avoid any future confusion.
will close this issue for now. feel free to re-open in case you wanna continue the discussion.
