### ISSUE TITLE
Attribute that specifies the name of the associated database

### ISSUE THREAD

**Issue by paolobriones** [dj-nitehawk/MongoDB.Entities#73]
Currently, in order to support multiple databases, an explicit call to DB.DatabaseFor() must be called. 
Can this be done via Attributes on the entity level, ie:

[Database("BookShopFILES")]
public class Picture : Entity {}

Thanks!

**Comment by dj-nitehawk** [comment]
the `DatabaseAttribute` was removed in v20 because attributes are an inferior choice for the purpose.

because they can only specify compile-time constants, we can't for example store the db name in `appsettings.json` or any other configuration provider and inject it in to our app during runtime.

besides, you only need to call `DB.DatabaseFor()` once at startup for each entity type you wanna store in a non-default database. you could even do it in the static constructor of the entity class if you prefer like this:
```csharp
        public class BookCover : Entity
        {
            public string Artist { get; set; }

            static BookCover() => DB.DatabaseFor<BookCover>("BookShopFILES");
        }

        private static async Task Main()
        {
            await DB.InitAsync("BookShop");
            await DB.InitAsync("BookShopFILES");

            await new BookCover { Artist = "paolobriones" }.SaveAsync();
        }
```

so, as you can see, there's no advantage at all for using an attribute to specify which database an entity needs to be stored in.

**Comment by paolobriones** [comment]
gotcha, i just didn't want to have the DB.DatabaseFor() call to be done away from the entity definition because anyone unfamiliar to the code will have to figure out how certain entities are routed to a different database, and also for projects with lots of entities, doing all the DatabaseFor() calls can end up with a large initialization section

**Comment by dj-nitehawk** [comment]
the static constructor is the best option for you then.
i'll also add that to the documentation.

**Comment by paolobriones** [comment]
Thanks! ill be using the static ctor to initialize the entities
