### ISSUE TITLE
Getting MongoDB.Driver.MongoWaitQueueFullException

### ISSUE THREAD

**Issue by atresnjo** [dj-nitehawk/MongoDB.Entities#82]
Version: 20.2.0

Testing with running MongoDB on Windows Server 2019 and Windows 10. Default setup, didn't change anything. Seems to happen when I for example use Parallel.ForEach.

Exception message: The wait queue for acquiring a connection to server 127.0.0.1:27017 is full.

Checked server status and only 112 connections have been made. What am I doing wrong?

![image](https://user-images.githubusercontent.com/41112852/95487810-17435d80-0995-11eb-8152-ec8a69a9f986.png)

![image](https://user-images.githubusercontent.com/41112852/95488417-cf710600-0995-11eb-9908-95089d55bf71.png)

Thanks!

**Comment by dj-nitehawk** [comment]
i believe you're experiencing a mongodb thread-pool starvation issue due to many tests executing in parallel. [see here for an explanation](https://jira.mongodb.org/browse/CSHARP-1180?focusedCommentId=1291455&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1291455)

they suggest either increase connection pool size, increase wait queue limit or both.

give this a try:
```csharp
            await DB.InitAsync(
                "db-name",
                new MongoClientSettings
                {
                    MinConnectionPoolSize = 100,
                    MaxConnectionPoolSize = 500
                });
```

if that doesn't work, don't use `Parallel.forEach` because even though you are awaiting the tasks inside the action of `forEach`, the  task returned by the action itself is not being awaited. or [do what i do here](https://github.com/dj-nitehawk/MongoDB.Entities/blob/1c8c8a187ca114f83942dfc25a821d44c649a7e5/Benchmark/Program.cs#L48) with Parallel.forEach and synchronously wait the tasks inside.

**Comment by paolobriones** [comment]
I've encountered this issue in the past, and I was processing data thru Parallel.ForEach() too, due to the amount of data I have to crunch, this led me to refactor the processing logic and eventually do the bulk save towards the end of the process.

**Comment by dj-nitehawk** [comment]
yeah Parallel.ForEach is more suitable for cpu bound work rather than io bound work like this.
best bet is to just do bulk saves like @paolobriones suggested.
also there's an [overload for adding multiple children](https://mongodb-entities.com/api/MongoDB.Entities.Many-1.html#MongoDB_Entities_Many_1_AddAsync_System_Collections_Generic_IEnumerable__0__MongoDB_Driver_IClientSessionHandle_System_Threading_CancellationToken_) to a relationship in one go.

**Comment by atresnjo** [comment]
Thanks for the help. I fixed it with your suggestions.
