### ISSUE TITLE
Referenced Relationships

### ISSUE THREAD

**Issue by curlyfro** [dj-nitehawk/MongoDB.Entities#84]
i love this api.  it's super cool and very natural -- entity objects should have extension methods on them for CRUD db functionality! :)

however, the referenced relationships are cool but super slow.

i created a collection of 200 objects.  each object has 3-4 references to another collection within it.  a query that used to take milliseconds against the owner collection now takes a few seconds with the added references.  I'm guessing nested collections will be magnitudes worse.  i see you're using a composite collection to do the relational lookups.  I'm not that familiar with the mongo API, but you couldn't get the native 'lookup' functions to work?

i tried to make the query faster by project.exclude my one-to-many property but that didn't work.  the property is still there :(  is there a way to remove the property from my query and do you think that will make it faster?

**Comment by dj-nitehawk** [comment]
thanks for the feedback!

it would help if i could see your entity definitions and how you query those. and also let me know the expected output.

would be better if you could give me a simplified example in the context of a bookshop/library that i can work with in order to come up with an optimized solution.

i do agree that the built-in relationship features may not fit some querying scenarios due to the inherent slowness of `$lookup`s in mongodb and the decision to go with composite/join collections to store the relationships.

but we may be able to optimize how we do it given an expected output.

if it cannot be optimized, then we can simply not use the `Many<T>` approach for references and use plain old `[ObjectId] string[] ForeignIDs` and do the lookups ourselves like we do with the official driver.
