### ISSUE TITLE
api blocking on concurrent mongo queries

### ISSUE THREAD

**Issue by ozkanonur** [dj-nitehawk/MongoDB.Entities#85]
In a rest service, when I stress test the endpoint that performs the READ process on MongoDB, the API stops responding almost forever even when I stop the stress test. Is there anything am I doing not correct?

## using version 13.0.0

Post Controller
```cs
return Ok(postService.getUiSchema(url));
```

Post Service
```cs
public object getUiSchema(string url)
{
    dynamic post = PostRepository.Find(p => p.url == url).FirstOrDefault();
    if (post == null) throw new Exception("PostNotFound");
    return post;
}
```

Post Repository
```cs
using api.src.shared.core.Entities;

namespace api.src.shared.core.Repositories
{
    public class PostRepository : BaseRepository.RepoBase<PostEntity>
    {

    }
}
```

Base Repository
```cs
public static TEntity Find(string id)
{
      return FindAsync<TEntity>(e => (e.ID == id && e.DeletedOn == null), null).GetAwaiter().GetResult().SingleOrDefault();
}

public static List<TEntity> Find(Expression<Func<TEntity, bool>> condition)
{
      return FindAsync<TEntity>(condition).GetAwaiter().GetResult();
}
```

**Comment by ozkanonur** [comment]
and the stress test is not even at medium level. Its just 5 seconds test with 50 connections open from 10 cpu threads.

**Comment by dj-nitehawk** [comment]
seems like you're doing the `sync-over-async` anti-pattern with `.GetAwaiter().GetResult()` which has the possibility of producing deadlocks.

here's a couple of things you can do/try (in order of efficiency):

1. upgrade to v20+ of the library. it has come a long way since v13 and is [async only](https://mongodb-entities.com/wiki/Async-Support.html#async-only-api).
2. try doing `DB.Find<TEntity>().Match(condition).ExecuteAsync().ConfigureAwait(false).GetAwaiter().GetResult()`.
3. use the sync api of the v13 library for ex: `DB.Find<TEntity>().Match(condition).Execute();`

both option 2 and 3 are not ideal as it leads to thread-pool starvation. in order to get the full benefit of async programming, you must make your app/ methods async from top to bottom. and try to never block async methods with `.GetAwaiter().GetResult()`. there is literally no advantages to doing so.
